/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STORAGE_H_RPCGEN
#define _STORAGE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct addtuple_1_argument {
	char *topic;
	char *text;
};
typedef struct addtuple_1_argument addtuple_1_argument;

#define STORAGE 99
#define STORAGEVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define initializeStorage 1
extern  enum clnt_stat initializestorage_1(void *, CLIENT *);
extern  bool_t initializestorage_1_svc(void *, struct svc_req *);
#define recoverTuple 2
extern  enum clnt_stat recovertuple_1(char *, char **, CLIENT *);
extern  bool_t recovertuple_1_svc(char *, char **, struct svc_req *);
#define addTuple 3
extern  enum clnt_stat addtuple_1(char *, char *, int *, CLIENT *);
extern  bool_t addtuple_1_svc(char *, char *, int *, struct svc_req *);
extern int storage_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define initializeStorage 1
extern  enum clnt_stat initializestorage_1();
extern  bool_t initializestorage_1_svc();
#define recoverTuple 2
extern  enum clnt_stat recovertuple_1();
extern  bool_t recovertuple_1_svc();
#define addTuple 3
extern  enum clnt_stat addtuple_1();
extern  bool_t addtuple_1_svc();
extern int storage_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_addtuple_1_argument (XDR *, addtuple_1_argument*);

#else /* K&R C */
extern bool_t xdr_addtuple_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STORAGE_H_RPCGEN */
