/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "storage.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
initializestorage_1(void *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, initializeStorage, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
recovertuple_1(char *topic, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, recoverTuple,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &topic,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
addtuple_1(char *topic, char *text, int *clnt_res,  CLIENT *clnt)
{
	addtuple_1_argument arg;
	arg.topic = topic;
	arg.text = text;
	return (clnt_call (clnt, addTuple, (xdrproc_t) xdr_addtuple_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
