/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_initializestorage_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (initializestorage_1_svc(result, rqstp));
}

int
_recovertuple_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (recovertuple_1_svc(*argp, result, rqstp));
}

int
_addtuple_1 (addtuple_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (addtuple_1_svc(argp->topic, argp->text, result, rqstp));
}

static void
storage_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *recovertuple_1_arg;
		addtuple_1_argument addtuple_1_arg;
	} argument;
	union {
		char *recovertuple_1_res;
		int addtuple_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case initializeStorage:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_initializestorage_1;
		break;

	case recoverTuple:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_recovertuple_1;
		break;

	case addTuple:
		_xdr_argument = (xdrproc_t) xdr_addtuple_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_addtuple_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!storage_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (STORAGE, STORAGEVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, STORAGE, STORAGEVER, storage_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (STORAGE, STORAGEVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, STORAGE, STORAGEVER, storage_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (STORAGE, STORAGEVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
