/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"

bool_t
xdr_addtuple_1_argument (XDR *xdrs, addtuple_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->topic, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->text, ~0))
		 return FALSE;
	return TRUE;
}
